/* HabitFlow Administrator Master 99+ Habit Library Catalog */

export const ADMIN_HABIT_LIBRARY = [
  // --- Category: Study & Education (18 Habits) ---
  { id: 'lib_std_1', name: 'Daily Study Session', category: 'Study', icon: 'goals', description: 'Focused learning session without distraction', defaultGoal: 25 },
  { id: 'lib_std_2', name: 'Read Non-Fiction Book', category: 'Study', icon: 'journal', description: 'Read at least 15–20 pages', defaultGoal: 22 },
  { id: 'lib_std_3', name: 'Learn JavaScript / Web Dev', category: 'Study', icon: 'analytics', description: 'Practice coding or build projects', defaultGoal: 20 },
  { id: 'lib_std_4', name: 'Complete Course Module', category: 'Study', icon: 'check', description: 'Watch lectures and complete lessons', defaultGoal: 18 },
  { id: 'lib_std_5', name: 'Solve Practice Questions', category: 'Study', icon: 'edit', description: 'Test knowledge with quizzes or problems', defaultGoal: 20 },
  { id: 'lib_std_6', name: 'Revise Flashcards / Notes', category: 'Study', icon: 'journal', description: 'Spaced repetition review', defaultGoal: 25 },
  { id: 'lib_std_7', name: 'Write Academic Summary', category: 'Study', icon: 'edit', description: 'Summarize key takeaways in writing', defaultGoal: 15 },
  { id: 'lib_std_8', name: 'Learn New Vocabulary', category: 'Study', icon: 'star', description: 'Master 5 new words in a target language', defaultGoal: 25 },
  { id: 'lib_std_9', name: 'Listen to Educational Podcast', category: 'Study', icon: 'journal', description: 'Expand knowledge on subjects', defaultGoal: 20 },
  { id: 'lib_std_10', name: 'Research Topic of Interest', category: 'Study', icon: 'search', description: 'Deep dive into specialized topics', defaultGoal: 15 },
  { id: 'lib_std_11', name: 'Practice Typing Speed', category: 'Study', icon: 'analytics', description: '10 minutes of typing drills', defaultGoal: 20 },
  { id: 'lib_std_12', name: 'Review Exam Syllabus', category: 'Study', icon: 'calendar', description: 'Check target deadlines and preparation', defaultGoal: 15 },
  { id: 'lib_std_13', name: 'Watch Tech Documentary', category: 'Study', icon: 'journal', description: 'Learn industry insights & history', defaultGoal: 10 },
  { id: 'lib_std_14', name: 'Read Industry Articles', category: 'Study', icon: 'search', description: 'Stay up-to-date with trends', defaultGoal: 20 },
  { id: 'lib_std_15', name: 'Solve LeetCode / Algorithmic Problem', category: 'Study', icon: 'analytics', description: 'Sharpen logic and problem solving', defaultGoal: 20 },
  { id: 'lib_std_16', name: 'Practice Math Drills', category: 'Study', icon: 'edit', description: 'Solve mental math or equations', defaultGoal: 18 },
  { id: 'lib_std_17', name: 'Study Grammar & Writing Rules', category: 'Study', icon: 'journal', description: 'Improve written communication', defaultGoal: 15 },
  { id: 'lib_std_18', name: 'Prepare Study Schedule', category: 'Study', icon: 'calendar', description: 'Organize study topics for the upcoming week', defaultGoal: 25 },

  // --- Category: Health & Nutrition (20 Habits) ---
  { id: 'lib_hea_1', name: 'Drink 3 Liters Water', category: 'Health', icon: 'star', description: 'Stay fully hydrated throughout the day', defaultGoal: 30 },
  { id: 'lib_hea_2', name: 'Sleep Before 11 PM', category: 'Health', icon: 'moon', description: 'Ensure 7–8 hours of quality sleep', defaultGoal: 25 },
  { id: 'lib_hea_3', name: 'Wake Up at 6:00 AM', category: 'Health', icon: 'sun', description: 'Start the day early and calm', defaultGoal: 25 },
  { id: 'lib_hea_4', name: 'Eat Fresh Whole Fruit', category: 'Health', icon: 'star', description: 'Consume natural vitamins and fibers', defaultGoal: 28 },
  { id: 'lib_hea_5', name: 'No Processed Sugar', category: 'Health', icon: 'cross', description: 'Avoid refined sweets and sugary beverages', defaultGoal: 22 },
  { id: 'lib_hea_6', name: 'Take Daily Multivitamins', category: 'Health', icon: 'check', description: 'Maintain essential nutrient levels', defaultGoal: 30 },
  { id: 'lib_hea_7', name: 'Prepare Healthy Meal', category: 'Health', icon: 'star', description: 'Cook fresh meals at home', defaultGoal: 22 },
  { id: 'lib_hea_8', name: 'No Fast Food / Junk Food', category: 'Health', icon: 'cross', description: 'Stick to clean home nutrition', defaultGoal: 25 },
  { id: 'lib_hea_9', name: 'Posture Check & Correction', category: 'Health', icon: 'check', description: 'Sit straight during desk work', defaultGoal: 28 },
  { id: 'lib_hea_10', name: '10 Minutes Sun Exposure', category: 'Health', icon: 'sun', description: 'Get natural Vitamin D in morning sunlight', defaultGoal: 25 },
  { id: 'lib_hea_11', name: 'Skincare Routine', category: 'Health', icon: 'star', description: 'Morning and night skin care hygiene', defaultGoal: 30 },
  { id: 'lib_hea_12', name: 'Floss Teeth at Night', category: 'Health', icon: 'check', description: 'Maintain dental hygiene', defaultGoal: 30 },
  { id: 'lib_hea_13', name: 'Drink Herbal Green Tea', category: 'Health', icon: 'star', description: 'Boost antioxidants', defaultGoal: 20 },
  { id: 'lib_hea_14', name: 'No Caffeine After 3 PM', category: 'Health', icon: 'moon', description: 'Protect night sleep quality', defaultGoal: 25 },
  { id: 'lib_hea_15', name: 'Cold Shower in Morning', category: 'Health', icon: 'sun', description: 'Boost alertness and immune response', defaultGoal: 20 },
  { id: 'lib_hea_16', name: 'Intermittent Fasting (16/8)', category: 'Health', icon: 'calendar', description: 'Allow digestive system recovery', defaultGoal: 20 },
  { id: 'lib_hea_17', name: 'Limit Screen Use Before Bed', category: 'Health', icon: 'screentime', description: 'No phone screen 30 mins before sleep', defaultGoal: 25 },
  { id: 'lib_hea_18', name: 'Eye Relaxation Exercises', category: 'Health', icon: 'screentime', description: '20-20-20 rule for screen fatigue', defaultGoal: 28 },
  { id: 'lib_hea_19', name: 'Eat Vegetables with Meals', category: 'Health', icon: 'star', description: 'Include greens in lunch and dinner', defaultGoal: 28 },
  { id: 'lib_hea_20', name: 'Track Daily Water Intake', category: 'Health', icon: 'analytics', description: 'Log hydration milestones', defaultGoal: 30 },

  // --- Category: Fitness & Exercise (18 Habits) ---
  { id: 'lib_fit_1', name: '10,000 Daily Steps', category: 'Fitness', icon: 'analytics', description: 'Stay active through walking', defaultGoal: 25 },
  { id: 'lib_fit_2', name: 'Gym / Strength Workout', category: 'Fitness', icon: 'goals', description: 'Weight training or resistance workout', defaultGoal: 20 },
  { id: 'lib_fit_3', name: '30-Minute Outdoor Jog', category: 'Fitness', icon: 'sun', description: 'Cardio endurance running', defaultGoal: 18 },
  { id: 'lib_fit_4', name: 'Morning Body Stretch', category: 'Fitness', icon: 'sun', description: '10 mins flex and joint warm-up', defaultGoal: 28 },
  { id: 'lib_fit_5', name: '50 Push-Ups Daily', category: 'Fitness', icon: 'check', description: 'Upper body endurance exercise', defaultGoal: 22 },
  { id: 'lib_fit_6', name: 'Plank Hold (2 Minutes)', category: 'Fitness', icon: 'goals', description: 'Core stability and endurance', defaultGoal: 22 },
  { id: 'lib_fit_7', name: 'Yoga / Vinyasa Session', category: 'Fitness', icon: 'star', description: 'Flexibility and breathing flow', defaultGoal: 15 },
  { id: 'lib_fit_8', name: 'Cycling / Bike Ride', category: 'Fitness', icon: 'sun', description: 'Cardiovascular leg workout', defaultGoal: 15 },
  { id: 'lib_fit_9', name: 'Jump Rope (1,000 Skips)', category: 'Fitness', icon: 'analytics', description: 'High intensity cardio training', defaultGoal: 18 },
  { id: 'lib_fit_10', name: 'Bodyweight Squats (100 Reps)', category: 'Fitness', icon: 'check', description: 'Lower body strength conditioning', defaultGoal: 20 },
  { id: 'lib_fit_11', name: 'Swimming Laps', category: 'Fitness', icon: 'star', description: 'Full body low impact swimming', defaultGoal: 12 },
  { id: 'lib_fit_12', name: 'Core Abdominals Workout', category: 'Fitness', icon: 'goals', description: '15 mins core circuit workout', defaultGoal: 18 },
  { id: 'lib_fit_13', name: 'Active Recovery Walk', category: 'Fitness', icon: 'sun', description: 'Light walk on rest days', defaultGoal: 25 },
  { id: 'lib_fit_14', name: 'HIIT Cardio Blast', category: 'Fitness', icon: 'goals', description: '20 mins high intensity interval training', defaultGoal: 15 },
  { id: 'lib_fit_15', name: 'Pull-Ups / Chin-Ups (20 Reps)', category: 'Fitness', icon: 'check', description: 'Upper body pull strength', defaultGoal: 18 },
  { id: 'lib_fit_16', name: 'Mobility & Foam Rolling', category: 'Fitness', icon: 'star', description: 'Muscle recovery and soft tissue release', defaultGoal: 20 },
  { id: 'lib_fit_17', name: 'Stair Climbing (15 Flights)', category: 'Fitness', icon: 'analytics', description: 'Take stairs instead of elevator', defaultGoal: 22 },
  { id: 'lib_fit_18', name: 'Track Daily Active Calories', category: 'Fitness', icon: 'analytics', description: 'Monitor physical calorie burn', defaultGoal: 25 },

  // --- Category: Personal & Lifestyle (16 Habits) ---
  { id: 'lib_per_1', name: 'Daily Journal Entry', category: 'Personal', icon: 'journal', description: 'Write notes, reflections, and thoughts', defaultGoal: 25 },
  { id: 'lib_per_2', name: 'Family & Loved Ones Time', category: 'Personal', icon: 'star', description: 'Quality uninterrupted family time', defaultGoal: 28 },
  { id: 'lib_per_3', name: 'Clean & Tidy Desk', category: 'Personal', icon: 'check', description: 'Organize workspace before ending day', defaultGoal: 28 },
  { id: 'lib_per_4', name: 'Express Daily Gratitude', category: 'Personal', icon: 'star', description: 'Write down 3 things you are grateful for', defaultGoal: 30 },
  { id: 'lib_per_5', name: 'Track Personal Expenses', category: 'Personal', icon: 'analytics', description: 'Log daily financial spending', defaultGoal: 30 },
  { id: 'lib_per_6', name: 'No Impulse Purchases', category: 'Personal', icon: 'cross', description: 'Stick strictly to budget plans', defaultGoal: 25 },
  { id: 'lib_per_7', name: 'Call a Friend or Relative', category: 'Personal', icon: 'star', description: 'Nurture personal relationships', defaultGoal: 12 },
  { id: 'lib_per_8', name: 'Read News / Current Affairs', category: 'Personal', icon: 'search', description: 'Stay informed about world developments', defaultGoal: 20 },
  { id: 'lib_per_9', name: 'Practice Creative Hobby', category: 'Personal', icon: 'edit', description: 'Painting, music, writing, or crafting', defaultGoal: 15 },
  { id: 'lib_per_10', name: 'Make Bed Immediately', category: 'Personal', icon: 'check', description: 'Complete first task of the morning', defaultGoal: 30 },
  { id: 'lib_per_11', name: 'Digital Declutter (Delete Unused Files)', category: 'Personal', icon: 'trash', description: 'Clean computer desktop and phone photos', defaultGoal: 15 },
  { id: 'lib_per_12', name: 'Practice Public Speaking / Vocal Exercises', category: 'Personal', icon: 'goals', description: 'Improve speech clarity and tone', defaultGoal: 15 },
  { id: 'lib_per_13', name: 'Organize Wardrobe / Closet', category: 'Personal', icon: 'check', description: 'Keep clothes neat and organized', defaultGoal: 10 },
  { id: 'lib_per_14', name: 'Water Household Plants', category: 'Personal', icon: 'star', description: 'Care for home greenery', defaultGoal: 15 },
  { id: 'lib_per_15', name: 'Review Monthly Financial Savings', category: 'Personal', icon: 'analytics', description: 'Check progress towards saving goals', defaultGoal: 4 },
  { id: 'lib_per_16', name: 'Nighttime Reflection', category: 'Personal', icon: 'moon', description: 'Reflect on wins and learnings before sleep', defaultGoal: 25 },

  // --- Category: Productivity & Work (16 Habits) ---
  { id: 'lib_prd_1', name: 'Deep Focus Work Block (90 Mins)', category: 'Productivity', icon: 'goals', description: 'Zero notification focus block', defaultGoal: 22 },
  { id: 'lib_prd_2', name: 'Plan Next Day Priorities', category: 'Productivity', icon: 'calendar', description: 'Write down top 3 tasks for tomorrow', defaultGoal: 25 },
  { id: 'lib_prd_3', name: 'Zero Inbox (Process Emails)', category: 'Productivity', icon: 'check', description: 'Organize and respond to messages', defaultGoal: 22 },
  { id: 'lib_prd_4', name: 'Pomodoro Sessions (4 Cycles)', category: 'Productivity', icon: 'analytics', description: '25m work / 5m break interval focus', defaultGoal: 20 },
  { id: 'lib_prd_5', name: 'No Social Media During Work', category: 'Productivity', icon: 'screentime', description: 'Block distractions during productive hours', defaultGoal: 22 },
  { id: 'lib_prd_6', name: 'Eat the Frog (Do Hardest Task First)', category: 'Productivity', icon: 'goals', description: 'Tackle high priority task in morning', defaultGoal: 20 },
  { id: 'lib_prd_7', name: 'Limit Social Media < 30 Mins', category: 'Productivity', icon: 'screentime', description: 'Cap recreational screen scrolling', defaultGoal: 25 },
  { id: 'lib_prd_8', name: 'Review Project Milestones', category: 'Productivity', icon: 'analytics', description: 'Check deadlines and project progress', defaultGoal: 20 },
  { id: 'lib_prd_9', name: 'Organize Digital Files & Cloud Storage', category: 'Productivity', icon: 'database', description: 'Keep cloud folders structured', defaultGoal: 15 },
  { id: 'lib_prd_10', name: 'Batch Process Administrative Tasks', category: 'Productivity', icon: 'check', description: 'Handle bills and quick chores together', defaultGoal: 18 },
  { id: 'lib_prd_11', name: 'Conduct Weekly Review', category: 'Productivity', icon: 'calendar', description: 'Assess weekly accomplishments and goals', defaultGoal: 4 },
  { id: 'lib_prd_12', name: 'Time Tracking Work Hours', category: 'Productivity', icon: 'analytics', description: 'Log hours spent on specific projects', defaultGoal: 22 },
  { id: 'lib_prd_13', name: 'Delegate or Automate Repetitive Work', category: 'Productivity', icon: 'settings', description: 'Streamline routine tasks', defaultGoal: 12 },
  { id: 'lib_prd_14', name: 'Clear Browser Tabs Before Ending Work', category: 'Productivity', icon: 'cross', description: 'Close unnecessary windows and tabs', defaultGoal: 25 },
  { id: 'lib_prd_15', name: 'Single-Tasking Only (No Multitasking)', category: 'Productivity', icon: 'goals', description: 'Focus on one activity at a time', defaultGoal: 20 },
  { id: 'lib_prd_16', name: 'Write Meeting Action Items', category: 'Productivity', icon: 'edit', description: 'Document next steps after discussions', defaultGoal: 18 },

  // --- Category: Mindfulness & Well-Being (15 Habits) ---
  { id: 'lib_mnd_1', name: '10-Minute Guided Meditation', category: 'Mindfulness', icon: 'star', description: 'Practice calm mindfulness and breathing', defaultGoal: 25 },
  { id: 'lib_mnd_2', name: 'Deep Breathing Exercises (Box Breathing)', category: 'Mindfulness', icon: 'sun', description: 'Calm central nervous system', defaultGoal: 25 },
  { id: 'lib_mnd_3', name: 'Silent Coffee / Tea Walk', category: 'Mindfulness', icon: 'sun', description: 'Mindful morning walk without phone', defaultGoal: 20 },
  { id: 'lib_mnd_4', name: 'Listen to Calming Ambient Sound', category: 'Mindfulness', icon: 'star', description: 'De-stress with natural acoustics', defaultGoal: 20 },
  { id: 'lib_mnd_5', name: 'No Phone First 30 Mins After Waking', category: 'Mindfulness', icon: 'screentime', description: 'Start morning mindfully', defaultGoal: 25 },
  { id: 'lib_mnd_6', name: 'Mindful Eating (No Screen During Lunch)', category: 'Mindfulness', icon: 'star', description: 'Focus on food sensory experience', defaultGoal: 22 },
  { id: 'lib_mnd_7', name: 'Practice Positive Affirmations', category: 'Mindfulness', icon: 'star', description: 'Reinforce self-confidence', defaultGoal: 25 },
  { id: 'lib_mnd_8', name: 'Spend 20 Mins in Nature', category: 'Mindfulness', icon: 'sun', description: 'Walk in park or green outdoors', defaultGoal: 18 },
  { id: 'lib_mnd_9', name: 'Perform Random Act of Kindness', category: 'Mindfulness', icon: 'star', description: 'Brighten someone else\'s day', defaultGoal: 15 },
  { id: 'lib_mnd_10', name: 'Progressive Muscle Relaxation', category: 'Mindfulness', icon: 'moon', description: 'Release physical tension before sleep', defaultGoal: 20 },
  { id: 'lib_mnd_11', name: 'Digital Detox Hour', category: 'Mindfulness', icon: 'screentime', description: '60 minutes completely disconnected from tech', defaultGoal: 20 },
  { id: 'lib_mnd_12', name: 'Practice Forgiveness & Letting Go', category: 'Mindfulness', icon: 'star', description: 'Clear mental resentment', defaultGoal: 20 },
  { id: 'lib_mnd_13', name: 'Stargazing / Evening Reflection', category: 'Mindfulness', icon: 'moon', description: 'Unwind under nighttime sky', defaultGoal: 15 },
  { id: 'lib_mnd_14', name: 'Body Scan Awareness', category: 'Mindfulness', icon: 'star', description: 'Mindful check-in with physical sensations', defaultGoal: 22 },
  { id: 'lib_mnd_15', name: 'Log Daily Mood & Energy', category: 'Mindfulness', icon: 'moodHappy', description: 'Track emotional trends', defaultGoal: 30 }
];
